# Phase 3: Data cleaning and Using Oracle
Group 12

## 1. Data cleaning

In [1]:
# Importing packages
import pandas as pd
import numpy as np

First, we read in all the files. The `dataset` folder is also attached to our submission.

In [2]:
# Reading in all seven datasets. Some were previously .csv already but others need to be converted
netflix_1 = pd.read_csv("datasets/NetFlix.csv")
netflix_2 = pd.read_csv("datasets/netflix_titles.csv")
disney = pd.read_csv("datasets/disney_plus_titles.csv")
rotten_tomatoes_movies = pd.read_csv("datasets/rotten_tomatoes_movies.csv")
imdb_title_ratings = pd.read_csv("datasets/title.ratings.tsv", sep="\t")
imdb_title_basics = pd.read_csv("datasets/title.basics.tsv", sep="\t")

### Netflix 1 Dataset

In [3]:
print("There are", len(netflix_1), "rows in this dataset before cleaning.")

There are 7787 rows in this dataset before cleaning.

In [4]:
# Replace missing values with None so Oracle can store it as null
netflix_1 = netflix_1.replace({np.nan: None})
netflix_1 = netflix_1.where(pd.notnull(netflix_1), None)

# Parsing every date_added value as a date. If one is invalid, just make it missing instead of throwing an error.
netflix_1["date_added"] = pd.to_datetime(
    netflix_1["date_added"],
    format="%d-%b-%y",
    errors="coerce"
)

# Renaming the 'rating' column to 'maturity_rating' to make it more clear
netflix_1 = netflix_1.rename(columns={"rating": "maturity_rating"})

# Constraining the date added to the pandemic period [2018,2021]
netflix_1 = netflix_1[
    (netflix_1["date_added"].dt.year >= 2018) &
    (netflix_1["date_added"].dt.year <= 2021)
]

# Convert duration into a number
netflix_1["duration"] = pd.to_numeric(netflix_1["duration"], errors="coerce")

# Replace missing values again because after converting dates and numbers, pandas may have created new missing values like NaT and NaN
netflix_1 = netflix_1.where(pd.notnull(netflix_1), None)

In [5]:
print("There are", len(netflix_1), "rows in this dataset after cleaning.")

There are 5922 rows in this dataset after cleaning.

### Netflix 2 Dataset

In [6]:
print("There are", len(netflix_2), "rows in this dataset before cleaning.")

There are 6234 rows in this dataset before cleaning.

In [7]:
# Replace missing values with None so Oracle can store it as NULL
netflix_2 = netflix_2.replace({np.nan: None})
netflix_2 = netflix_2.where(pd.notnull(netflix_2), None)

# Parsing every date_added value as a date. If one is invalid, just make it missing instead of throwing an error.
netflix_2["date_added"] = pd.to_datetime(
    netflix_2["date_added"],
    format="%B %d, %Y",
    errors="coerce"
)

# Renaming the 'rating' column to 'maturity_rating' to make it more clear
netflix_2 = netflix_2.rename(columns={"rating": "maturity_rating"})

# Constraining the date added to the pandemic period [2018,2021]
netflix_2 = netflix_2[
    (netflix_2["date_added"].dt.year >= 2018) &
    (netflix_2["date_added"].dt.year <= 2021)
]

# Convert duration into a number
netflix_2["duration"] = pd.to_numeric(netflix_2["duration"], errors="coerce")

# Replace missing values again because after converting dates and numbers, pandas may have created new missing values like NaT and NaN
netflix_2 = netflix_2.where(pd.notnull(netflix_2), None)

### Disney+ Dataset

In [8]:
print("There are", len(disney), "rows in this dataset before cleaning.")

There are 1450 rows in this dataset before cleaning.

In [9]:
# Replace missing values with None so Oracle can store it as NULL
disney = disney.replace({np.nan: None})
disney = disney.where(pd.notnull(disney), None)

# Parsing every date_added value as a date. If one is invalid, just make it missing instead of throwing an error.
disney["date_added"] = pd.to_datetime(
    disney["date_added"],
    format="%B %d, %Y",
    errors="coerce"
)

# Renaming the 'rating' column to 'maturity_rating' to make it more clear
disney = disney.rename(columns={"rating": "maturity_rating"})

# Constraining the date added to the pandemic period [2018,2021]
disney = disney[
    (disney["date_added"].dt.year >= 2018) &
    (disney["date_added"].dt.year <= 2021)
]

# Convert duration into a number
disney["duration"] = pd.to_numeric(disney["duration"], errors="coerce")

# Replace missing values again because after converting dates and numbers, pandas may have created new missing values like NaT and NaN
disney = disney.where(pd.notnull(disney), None)

In [10]:
print("There are", len(disney), "rows in this dataset after cleaning.")

There are 1447 rows in this dataset after cleaning.

### Rotten Tomatoes Movies Dataset

In [11]:
print("There are", len(rotten_tomatoes_movies), "rows in this dataset before cleaning.")

There are 143258 rows in this dataset before cleaning.

In [12]:
# Rename rating to maturity_rating for clarification
rotten_tomatoes_movies = rotten_tomatoes_movies.rename(columns={"rating": "maturity_rating"})

# Drop rows with missing maturity rating
rotten_tomatoes_movies = rotten_tomatoes_movies.dropna(subset=["maturity_rating"])

# Drop rows with missing audienceScore
rotten_tomatoes_movies = rotten_tomatoes_movies.dropna(subset=["audienceScore"])

# Drop rows with missing tomatoMeter
rotten_tomatoes_movies = rotten_tomatoes_movies.dropna(subset=["tomatoMeter"])

# Standardizing the maturity ratings so it matches the Netflix and Disney+ datasets (including a dash between letters, i.e. changing TVPG to TV-PG)
rating_map = {
    "TVPG": "TV-PG",
    "TV14": "TV-14",
    "TVMA": "TV-MA",
    "TVG": "TV-G",
    "TVY7": "TV-Y7"
}

rotten_tomatoes_movies["maturity_rating"] = (
    rotten_tomatoes_movies["maturity_rating"]
    .replace(rating_map)
)

# Convert releasedateStreaming to datetime
rotten_tomatoes_movies["releaseDateStreaming"] = pd.to_datetime(
    rotten_tomatoes_movies["releaseDateStreaming"],
    errors="coerce"
)

# Keep only 2018-2021 for releasedateStreaming
rotten_tomatoes_movies = rotten_tomatoes_movies[
    rotten_tomatoes_movies["releaseDateStreaming"].dt.year.between(2018, 2021)
]

In [13]:
print("There are", len(rotten_tomatoes_movies), "rows in this dataset after cleaning.")

There are 1642 rows in this dataset after cleaning.

### IMDB Title Basics Dataset

In [14]:
imdb_title_basics.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Poor Pierrot,Pauvre Pierrot,0,1892,\N,5,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,Short

In [15]:
print("There are", len(imdb_title_basics), "rows in this dataset before cleaning.")

There are 12287568 rows in this dataset before cleaning.

In [16]:
# Python is currently storing startYear as text, convert to numeric
imdb_title_basics["startYear"] = pd.to_numeric(
    imdb_title_basics["startYear"],
    errors="coerce"
)

# Filter to be within pandemic period [2018,2021]
imdb_title_basics = imdb_title_basics[
    imdb_title_basics["startYear"].between(2018, 2021)
]

# Even aftering filtering down to only 2018-2021, the dataset is still too large (about 190,000 rows). Although we were going to do this in SQL using a natural join, Oracle 
# allow us to CREATE TABLE or INSERT into SQL because it exceeds user quota. Therefore, in Python, we are going to only keep te rows where the primary title is in
# either the netflix_1, netflix_2, or Disney datasets.
all_titles = pd.concat([
    netflix_1["title"],
    netflix_2["title"],
    disney["title"]
]).dropna().unique()

imdb_title_basics = imdb_title_basics[
    imdb_title_basics["primaryTitle"].isin(all_titles)
]

In [17]:
imdb_title_basics = imdb_title_basics.replace(r'\N', None)

In [18]:
pd.DataFrame(imdb_title_basics)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
67649,tt0069049,movie,The Other Side of the Wind,The Other Side of the Wind,0,2018.0,None,122,Drama
350035,tt0365545,movie,Nappily Ever After,Nappily Ever After,0,2018.0,None,98,"Comedy,Drama,Romance"
774612,tt0800325,movie,The Dirt,The Dirt,0,2019.0,None,107,"Biography,Comedy,Drama"
842188,tt0870154,movie,Jungle Cruise,Jungle Cruise,0,2021.0,None,127,"Action,Adventure,Comedy"
884719,tt0914376,tvMiniSeries,The Innocent Man,The Innocent Man,0,2018.0,2018,45,"Crime,Documentary"
...,...,...,...,...,...,...,...,...,...
12285575,tt9912510,short,The Circle,The Circle,0,2018.0,None,3,Short
12286349,tt9914156,tvEpisode,Triple Frontier,Triple Frontier,0,2019.0,None,None,Talk-Show
12286667,tt9914844,short,Blood Money,Blood Money,0,2019.0,None,None,"Short,Thriller"
12287092,tt9915838,tvEpisode,Love,Love,0,2019.0,None,None,Comedy
12287244,tt9916170,movie,The Rehearsal,O Ensaio,0,2019.0,None,51,Drama

In [19]:
print("There are", len(imdb_title_basics), "rows in this dataset after cleaning.")

There are 14985 rows in this dataset after cleaning.

### IMDB Title Ratings Dataset

In [20]:
print("There are", len(imdb_title_ratings), "rows in this dataset before cleaning.")

There are 1634568 rows in this dataset before cleaning.

In [21]:
# Only keeping the tconst that is also in the imdb_title_basics dataset. Otherwise, we would have natural left joined in SQL and it automatically would have 
# kept only the rows where the tconst is the same, but reading in the raw dataset would have exceeded the quota in Oracle.
imdb_title_ratings = imdb_title_ratings[
    imdb_title_ratings["tconst"].isin(imdb_title_basics["tconst"])
]

In [22]:
print("There are", len(imdb_title_ratings), "rows in this dataset after cleaning.")

There are 5786 rows in this dataset after cleaning.

### Write all cleaned datasets to a new CSV

In [23]:
netflix_1.to_csv("Cleaned/netflix_1_cleaned.csv", index=False)
netflix_2.to_csv("Cleaned/netflix_2_cleaned.csv", index=False)
disney.to_csv("Cleaned/disney_cleaned.csv", index=False)
rotten_tomatoes_movies.to_csv("Cleaned/rotten_tomatoes_movies_cleaned.csv", index=False)
imdb_title_ratings.to_csv("Cleaned/imdb_title_ratings_cleaned.csv", index=False)
imdb_title_basics.to_csv("Cleaned/imdb_title_basics_cleaned.csv", index=False)