# Phase 3: Data cleaning and Using Oracle
Group 12

## 1. Data cleaning

In [1]:
# Importing packages
import pandas as pd
import numpy as np

First, we read in all the files. The `dataset` folder is also attached to our submission.

In [2]:
# Reading in all seven datasets. Some were previously .csv already but others need to be converted
netflix_1 = pd.read_csv("datasets/NetFlix.csv")
netflix_2 = pd.read_csv("datasets/netflix_titles.csv")
disney = pd.read_csv("datasets/disney_plus_titles.csv")
rotten_tomatoes_movies = pd.read_csv("datasets/rotten_tomatoes_movies.csv")
imdb_title_ratings = pd.read_csv("datasets/title.ratings.tsv", sep="\t")
imdb_title_basics = pd.read_csv("datasets/title.basics.tsv", sep="\t")

### Netflix 1 Dataset

In [3]:
print("There are", len(netflix_1), "rows in this dataset before cleaning.")

There are 7787 rows in this dataset before cleaning.

In [3]:
# Replace missing values with None so Oracle can store it as null
netflix_1 = netflix_1.replace({np.nan: None})
netflix_1 = netflix_1.where(pd.notnull(netflix_1), None)

# Parsing every date_added value as a date. If one is invalid, just make it missing instead of throwing an error.
netflix_1["date_added"] = pd.to_datetime(
    netflix_1["date_added"],
    format="%d-%b-%y",
    errors="coerce"
)

# Renaming the 'rating' column to 'maturity_rating' to make it more clear
netflix_1 = netflix_1.rename(columns={"rating": "maturity_rating"})

# Constraining the date added to the pandemic period [2018,2021]
netflix_1 = netflix_1[
    (netflix_1["date_added"].dt.year >= 2018) &
    (netflix_1["date_added"].dt.year <= 2021)
]

# Convert duration into a number
netflix_1["duration"] = pd.to_numeric(netflix_1["duration"], errors="coerce")

# Replace missing values again because after converting dates and numbers, pandas may have created new missing values like NaT and NaN
netflix_1 = netflix_1.where(pd.notnull(netflix_1), None)

In [5]:
print("There are", len(netflix_1), "rows in this dataset after cleaning.")

There are 5922 rows in this dataset after cleaning.

### Netflix 2 Dataset

In [6]:
print("There are", len(netflix_2), "rows in this dataset before cleaning.")

There are 6234 rows in this dataset before cleaning.

In [36]:

# Replace missing values with None so Oracle can store it as NULL
netflix_2 = netflix_2.replace({np.nan: None})
netflix_2 = netflix_2.where(pd.notnull(netflix_2), None)

# Parsing every date_added value as a date. If one is invalid, just make it missing instead of throwing an error.
netflix_2["date_added"] = pd.to_datetime(
    netflix_2["date_added"],
    format="%B %d, %Y",
    errors="coerce"
)

# Renaming the 'rating' column to 'maturity_rating' to make it more clear
netflix_2 = netflix_2.rename(columns={"rating": "maturity_rating"})

# Constraining the date added to the pandemic period [2018,2021]
netflix_2 = netflix_2[
    (netflix_2["date_added"].dt.year >= 2018) &
    (netflix_2["date_added"].dt.year <= 2021)
]

# Convert duration into a number
netflix_2["duration"] = pd.to_numeric(netflix_2["duration"], errors="coerce")

# Replace missing values again because after converting dates and numbers, pandas may have created new missing values like NaT and NaN
netflix_2 = netflix_2.where(pd.notnull(netflix_2), None)
netflix_2 = netflix_2.replace({np.nan: None})

In [37]:
netflix_2

,show_id,type,title,director,cast,country,date_added,release_year,maturity_rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019-09-09,2019,TV-PG,None,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
2,70234439,TV Show,Transformers Prime,None,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2018-09-08,2013,TV-Y7-FV,None,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,None,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2018-09-08,2016,TV-Y7,None,Kids' TV,When a prison ship crash unleashes hundreds of...
26,80244601,TV Show,Castle of Stars,None,"Chaiyapol Pupart, Jintanutda Lummakanon, Worra...",None,2018-09-07,2015,TV-14,None,"International TV Shows, Romantic TV Shows, TV ...",As four couples with different lifestyles go t...
27,80203094,Movie,City of Joy,Madeleine Gavin,None,"United States,",2018-09-07,2018,TV-MA,None,Documentaries,Women who've been sexually brutalized in war-t...
...,...,...,...,...,...,...,...,...,...,...,...,...
5542,80049281,Movie,Secret in Their Eyes,Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...","United States, United Kingdom, Spain, South Korea",2018-04-01,2015,PG-13,None,"Dramas, Thrillers",A former FBI investigator reopens the haunting...
5543,70084328,Movie,The Aerial,Esteban Sapir,"Rafael Ferro, Sol Moreno, Jonathan Sandor, Ale...",Argentina,2018-04-01,2007,TV-MA,None,"Dramas, International Movies, Sci-Fi & Fantasy","In the City Without a Voice, only faceless sin..."
5544,70099610,Movie,The Duchess,Saul Dibb,"Keira Knightley, Ralph Fiennes, Charlotte Ramp...","United Kingdom, Italy, France, United States",2018-04-01,2008,PG-13,None,"Dramas, International Movies, Romantic Movies","To compensate for her unhappy marriage, young ..."
5545,80217041,Movie,The Search for Life in Space,Stephen Amezdroz,None,United States,2018-04-01,2016,TV-G,None,Documentaries,To determine whether we're alone in the univer...
5546,80156408,Movie,Una,Benedict Andrews,"Rooney Mara, Ben Mendelsohn, Riz Ahmed, Ruby S...","United Kingdom, Canada, United States",2018-04-01,2016,R,None,"Dramas, International Movies",A young woman tracks down the older man who pr...

### Disney+ Dataset

In [8]:
print("There are", len(disney), "rows in this dataset before cleaning.")

There are 1450 rows in this dataset before cleaning.

In [ ]:

# Replace missing values with None so Oracle can store it as NULL
disney = disney.replace({np.nan: None})
disney = disney.where(pd.notnull(disney), None)

# Parsing every date_added value as a date. If one is invalid, just make it missing instead of throwing an error.
disney["date_added"] = pd.to_datetime(
    disney["date_added"],
    format="%B %d, %Y",
    errors="coerce"
)

# Renaming the 'rating' column to 'maturity_rating' to make it more clear
disney = disney.rename(columns={"rating": "maturity_rating"})

# Constraining the date added to the pandemic period [2018,2021]
disney = disney[
    (disney["date_added"].dt.year >= 2018) &
    (disney["date_added"].dt.year <= 2021)
]

# Convert duration into a number
disney["duration"] = pd.to_numeric(disney["duration"], errors="coerce")

# Replace missing values again because after converting dates and numbers, pandas may have created new missing values like NaT and NaN
disney = disney.where(pd.notnull(disney), None)
disney = disney.replace({np.nan: None})

In [10]:
print("There are", len(disney), "rows in this dataset after cleaning.")

There are 1447 rows in this dataset after cleaning.

### Rotten Tomatoes Movies Dataset

In [11]:
print("There are", len(rotten_tomatoes_movies), "rows in this dataset before cleaning.")

There are 143258 rows in this dataset before cleaning.

In [ ]:
# Rename rating to maturity_rating for clarification
rotten_tomatoes_movies = rotten_tomatoes_movies.rename(columns={"rating": "maturity_rating"})

# Drop rows with missing maturity rating
rotten_tomatoes_movies = rotten_tomatoes_movies.dropna(subset=["maturity_rating"])

# Drop rows with missing audienceScore
rotten_tomatoes_movies = rotten_tomatoes_movies.dropna(subset=["audienceScore"])

# Drop rows with missing tomatoMeter
rotten_tomatoes_movies = rotten_tomatoes_movies.dropna(subset=["tomatoMeter"])

# Standardizing the maturity ratings so it matches the Netflix and Disney+ datasets (including a dash between letters, i.e. changing TVPG to TV-PG)
rating_map = {
    "TVPG": "TV-PG",
    "TV14": "TV-14",
    "TVMA": "TV-MA",
    "TVG": "TV-G",
    "TVY7": "TV-Y7"
}

rotten_tomatoes_movies["maturity_rating"] = (
    rotten_tomatoes_movies["maturity_rating"]
    .replace(rating_map)
)

# Convert releasedateStreaming to datetime
rotten_tomatoes_movies["releaseDateStreaming"] = pd.to_datetime(
    rotten_tomatoes_movies["releaseDateStreaming"],
    errors="coerce"
)

rotten_tomatoes_movies['releaseDateTheaters'] = pd.to_datetime(rotten_tomatoes_movies['releaseDateTheaters'], errors='coerce')
rotten_tomatoes_movies['earliest_date'] = rotten_tomatoes_movies[['releaseDateTheaters', 'releaseDateStreaming']].min(axis=1)
rotten_tomatoes_movies['releaseYear'] = rotten_tomatoes_movies['earliest_date'].dt.year


# Keep only 2018-2021 for releasedateStreaming
rotten_tomatoes_movies = rotten_tomatoes_movies[
    rotten_tomatoes_movies["releaseDateStreaming"].dt.year.between(2018, 2021)
]

rotten_tomatoes_movies = rotten_tomatoes_movies[["id", "title", "audienceScore", "tomatoMeter", "maturity_rating", "releaseYear"]]
rotten_tomatoes_movies = rotten_tomatoes_movies.replace({np.nan: None})

KeyError: 'releaseDateStreaming'

In [20]:
all_titles = pd.concat([
    netflix_1["title"],
    netflix_2["title"],
    disney["title"]
]).dropna().unique()

rotten_tomatoes_movies = rotten_tomatoes_movies[
    rotten_tomatoes_movies["title"].isin(all_titles)
]

In [21]:
print("There are", len(rotten_tomatoes_movies), "rows in this dataset after cleaning.")

There are 295 rows in this dataset after cleaning.

### IMDB Title Basics Dataset

In [14]:
imdb_title_basics.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Poor Pierrot,Pauvre Pierrot,0,1892,\N,5,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,Short

In [15]:
print("There are", len(imdb_title_basics), "rows in this dataset before cleaning.")

There are 12287568 rows in this dataset before cleaning.

In [31]:
# Python is currently storing startYear as text, convert to numeric
imdb_title_basics["startYear"] = pd.to_numeric(
    imdb_title_basics["startYear"],
    errors="coerce"
)

# Filter to be within pandemic period [2018,2021]
imdb_title_basics = imdb_title_basics[
    imdb_title_basics["startYear"].between(2018, 2021)
]

# Even aftering filtering down to only 2018-2021, the dataset is still too large (about 190,000 rows). Although we were going to do this in SQL using a natural join, Oracle 
# allow us to CREATE TABLE or INSERT into SQL because it exceeds user quota. Therefore, in Python, we are going to only keep te rows where the primary title is in
# either the netflix_1, netflix_2, or Disney datasets.
all_titles = pd.concat([
    netflix_1["title"],
    netflix_2["title"],
    disney["title"]
]).dropna().unique()

imdb_title_basics = imdb_title_basics[
    imdb_title_basics["primaryTitle"].isin(all_titles)
]

In [32]:
imdb_title_basics = imdb_title_basics.replace(r'\N', None)

In [33]:
pd.DataFrame(imdb_title_basics)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
67649,tt0069049,movie,The Other Side of the Wind,The Other Side of the Wind,0,2018.0,None,122,Drama
350035,tt0365545,movie,Nappily Ever After,Nappily Ever After,0,2018.0,None,98,"Comedy,Drama,Romance"
774612,tt0800325,movie,The Dirt,The Dirt,0,2019.0,None,107,"Biography,Comedy,Drama"
842188,tt0870154,movie,Jungle Cruise,Jungle Cruise,0,2021.0,None,127,"Action,Adventure,Comedy"
884719,tt0914376,tvMiniSeries,The Innocent Man,The Innocent Man,0,2018.0,2018,45,"Crime,Documentary"
...,...,...,...,...,...,...,...,...,...
12286349,tt9914156,tvEpisode,Triple Frontier,Triple Frontier,0,2019.0,None,None,Talk-Show
12286493,tt9914468,short,One Night Stand,One Night Stand,0,2019.0,None,15,"Short,Thriller"
12286667,tt9914844,short,Blood Money,Blood Money,0,2019.0,None,None,"Short,Thriller"
12287092,tt9915838,tvEpisode,Love,Love,0,2019.0,None,None,Comedy
12287244,tt9916170,movie,The Rehearsal,O Ensaio,0,2019.0,None,51,Drama

In [19]:
print("There are", len(imdb_title_basics), "rows in this dataset after cleaning.")

There are 14985 rows in this dataset after cleaning.

### IMDB Title Ratings Dataset

In [20]:
print("There are", len(imdb_title_ratings), "rows in this dataset before cleaning.")

There are 1634568 rows in this dataset before cleaning.

In [21]:
# Only keeping the tconst that is also in the imdb_title_basics dataset. Otherwise, we would have natural left joined in SQL and it automatically would have 
# kept only the rows where the tconst is the same, but reading in the raw dataset would have exceeded the quota in Oracle.
imdb_title_ratings = imdb_title_ratings[
    imdb_title_ratings["tconst"].isin(imdb_title_basics["tconst"])
]

In [22]:
print("There are", len(imdb_title_ratings), "rows in this dataset after cleaning.")

There are 5786 rows in this dataset after cleaning.

### Write all cleaned datasets to a new CSV

In [23]:
netflix_1.to_csv("Cleaned/netflix_1_cleaned.csv", index=False)
netflix_2.to_csv("Cleaned/netflix_2_cleaned.csv", index=False)
disney.to_csv("Cleaned/disney_cleaned.csv", index=False)
rotten_tomatoes_movies.to_csv("Cleaned/rotten_tomatoes_movies_cleaned.csv", index=False)
imdb_title_ratings.to_csv("Cleaned/imdb_title_ratings_cleaned.csv", index=False)
imdb_title_basics.to_csv("Cleaned/imdb_title_basics_cleaned.csv", index=False)

## 2. ER Diagram

## 3. Database schema

## 4. Insert into Oracle

In [7]:
import oracledb
import csv

In [30]:
dsn = oracledb.makedsn("localhost", 1522, service_name="stu")
connection = oracledb.connect(user="ora_lding04", password="a88101027", dsn=dsn)
cur = connection.cursor()

In [27]:
cur.execute("DROP TABLE imdb_title_basics")
cur.execute("DROP TABLE netflix_1")
cur.execute("DROP TABLE netflix_2")
cur.execute("DROP TABLE disney_plus")
cur.execute("""
            DROP VIEW all_streaming_movies
            """)
cur.execute("DROP TABLE imdb_ratings")
cur.execute("DROP TABLE rotten_tomatoes")
cur.execute("PURGE RECYCLEBIN")
connection.commit()

### Netflix 1

In [28]:
cur.execute("""
    CREATE TABLE netflix_1 (
        show_id VARCHAR2(20) NOT NULL PRIMARY KEY,
        Type VARCHAR2(50),
        Title VARCHAR2(500),
        Director VARCHAR2(500),
        Cast VARCHAR2(1000),
        Country VARCHAR2(200),
        Date_added DATE,
        release_year NUMBER(4),
        matuarity_rating VARCHAR2(10),
        duration VARCHAR2(50),
        genres VARCHAR2(500),
        description VARCHAR(1000)
    )
""")

In [29]:
data_to_insert_netflix = netflix_1.values.tolist()
cur.executemany("INSERT INTO netflix_1 VALUES (:1, :2, :3, :4, :5, :6, TO_DATE(:7, 'YYYY-MM-DD'), :8, :9, :10, :11, :12)", data_to_insert_netflix)
connection.commit()

### Netflix 2

In [30]:
cur.execute("""
    CREATE TABLE netflix_2 (
        show_id VARCHAR2(20) NOT NULL PRIMARY KEY,
        Type VARCHAR2(50),
        Title VARCHAR2(500),
        Director VARCHAR2(500),
        Cast VARCHAR2(1000),
        Country VARCHAR2(200),
        Date_added DATE,
        release_year NUMBER(4),
        matuarity_rating VARCHAR2(10),
        duration VARCHAR2(50),
        listed_in VARCHAR2(500),
        description VARCHAR(1000)
    )
""")

In [33]:
netflix_2.head()

,show_id,type,title,director,cast,country,date_added,release_year,maturity_rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019-09-09,2019,TV-PG,NaN,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
2,70234439,TV Show,Transformers Prime,None,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2018-09-08,2013,TV-Y7-FV,NaN,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,None,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2018-09-08,2016,TV-Y7,NaN,Kids' TV,When a prison ship crash unleashes hundreds of...
26,80244601,TV Show,Castle of Stars,None,"Chaiyapol Pupart, Jintanutda Lummakanon, Worra...",None,2018-09-07,2015,TV-14,NaN,"International TV Shows, Romantic TV Shows, TV ...",As four couples with different lifestyles go t...
27,80203094,Movie,City of Joy,Madeleine Gavin,None,"United States,",2018-09-07,2018,TV-MA,NaN,Documentaries,Women who've been sexually brutalized in war-t...

In [38]:
data_to_insert_netflix_2 = netflix_2.values.tolist()
cur.executemany("INSERT INTO netflix_2 VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9, :10, :11, :12)", data_to_insert_netflix_2)
connection.commit()

### Disney plus

In [39]:
cur.execute("""
    CREATE TABLE disney_plus (
        show_id VARCHAR2(20) NOT NULL PRIMARY KEY,
        Type VARCHAR2(50),
        Title VARCHAR2(500),
        Director VARCHAR2(500),
        Cast VARCHAR2(500),
        Country VARCHAR2(200),
        Date_added DATE,
        release_year NUMBER(4),
        matuarity_rating VARCHAR2(10),
        duration VARCHAR2(50),
        listed_in VARCHAR2(500),
        description VARCHAR(1000)
    )
""")

In [43]:
data_to_insert_disney = disney.values.tolist()
cur.executemany("INSERT INTO disney_plus VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9, :10, :11, :12)", data_to_insert_disney)
connection.commit()

### Remove duplicates across these three datasets

In [48]:
cur.execute("""
            DROP VIEW all_streaming_movies
            """)

In [50]:
cur.execute("""
CREATE TABLE all_media_titles AS
SELECT show_id, title, director, country, release_year, matuarity_rating, 'Netflix' as source FROM netflix_1
UNION
SELECT show_id, title, director, country, release_year, matuarity_rating, 'Netflix' as source FROM netflix_2
UNION
SELECT show_id, title, director, country, release_year, matuarity_rating, 'Disney' as source FROM disney_plus
""")

In [53]:
cur.execute("DROP TABLE netflix_1")
cur.execute("DROP TABLE netflix_2")
cur.execute("DROP TABLE disney_plus")

In [54]:
cur.execute("PURGE RECYCLEBIN")
connection.commit()

In [56]:
cur.execute("ALTER TABLE all_media_titles ADD CONSTRAINT unq_title_year UNIQUE (title, release_year)")

### IMDB Title Basics

In [60]:
cur.execute("""
    CREATE TABLE imdb_title_basics (
    tconst VARCHAR2(20) NOT NULL PRIMARY KEY,
    titleType VARCHAR2(50),
    primaryTitle VARCHAR2(500),
    originalTitle VARCHAR2(500),
    isAdult NUMBER(1),
    startYear NUMBER(4),
    endYear NUMBER(4),
    runtimeMinutes INTEGER,
    Genres VARCHAR2(500),
    CONSTRAINT fk_imdb_to_media 
    FOREIGN KEY (primaryTitle, startYear) 
    REFERENCES all_media_titles (title, release_year)
)
""")

In [35]:
imdb_title_basics.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
67649,tt0069049,movie,The Other Side of the Wind,The Other Side of the Wind,0,2018.0,None,122,Drama
350035,tt0365545,movie,Nappily Ever After,Nappily Ever After,0,2018.0,None,98,"Comedy,Drama,Romance"
774612,tt0800325,movie,The Dirt,The Dirt,0,2019.0,None,107,"Biography,Comedy,Drama"
842188,tt0870154,movie,Jungle Cruise,Jungle Cruise,0,2021.0,None,127,"Action,Adventure,Comedy"
884719,tt0914376,tvMiniSeries,The Innocent Man,The Innocent Man,0,2018.0,2018,45,"Crime,Documentary"

In [37]:
data_to_insert = imdb_title_basics.values.tolist()

In [39]:
cur.executemany("INSERT INTO imdb_title_basics VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9)", data_to_insert, batcherrors=True)
errors = cur.getbatcherrors()
print(f"Successfully inserted {len(data_to_insert) - len(errors)} rows.")
connection.commit()

Successfully inserted 4034 rows.

### IMDB Title Ratings

In [61]:
cur.execute("""
    CREATE TABLE imdb_ratings (
        tconst VARCHAR2(20) NOT NULL PRIMARY KEY,
        average_ratings DECIMAL(3,1),
        numVotes INTEGER
    )
""")

In [62]:
data_to_insert_imdb_ratings = imdb_title_ratings.values.tolist()
cur.executemany("INSERT INTO imdb_ratings VALUES (:1, :2, :3)", data_to_insert_imdb_ratings)
connection.commit()

In [22]:
cur.execute("DROP TABLE rotten_tomatoes")

### Rotten Tomatoes

In [23]:
cur.execute("""
    CREATE TABLE rotten_tomatoes (
        id VARCHAR2(200) NOT NULL PRIMARY KEY,
        Title VARCHAR2(500),
        audienceScore INTEGER,
        tomatoMeter INTEGER,
        maturity_rating VARCHAR2(10),
        releaseYear NUMBER(4),
        CONSTRAINT fk_rt_to_media 
        FOREIGN KEY (Title, releaseYear) 
        REFERENCES all_media_titles (title, release_year)
    )
""")

In [24]:
rotten_tomatoes_movies.head()

,id,title,audienceScore,tomatoMeter,maturity_rating,releaseYear
5,adrift_2018,Adrift,65.0,69.0,PG-13,2018.0
146,robin_hood_2018,Robin Hood,40.0,15.0,PG-13,2018.0
360,hes_out_there,He's Out There,32.0,43.0,R,2018.0
995,lady_and_the_tramp_2019,Lady and the Tramp,50.0,66.0,PG,2020.0
1366,ghosts_of_war,Ghosts of War,44.0,40.0,R,2020.0

In [25]:
data_to_insert_rt = rotten_tomatoes_movies.values.tolist()

In [26]:
cur.executemany("INSERT INTO rotten_tomatoes VALUES (:1, :2, :3, :4, :5, :6)", data_to_insert_rt, batcherrors=True)
errors = cur.getbatcherrors()
for error in errors:
    print(f"Row {error.offset} failed with error: {error.message}")

# 3. Commit the successful rows
connection.commit()
print(f"Successfully inserted {len(data_to_insert_rt) - len(errors)} rows.")

Row 1 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 3 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 15 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 22 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 24 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 26 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 27 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 30 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 35 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 43 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 49 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 51 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 62 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 65 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 67 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 69 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 70 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 72 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 73 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 80 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 81 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 84 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 85 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 88 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 90 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 94 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 97 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 98 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 101 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 102 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 103 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 104 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 105 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 113 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 115 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 117 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 118 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 119 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 123 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 125 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 126 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 127 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 134 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 136 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 138 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 139 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 140 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 157 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 159 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 161 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 170 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 173 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 176 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 177 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 178 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 189 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 191 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 193 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 198 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 203 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 204 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 222 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 270 failed with error: ORA-00001: unique constraint (ORA_LDING04.SYS_C002759010) violated
Help: https://docs.oracle.com/error-help/db/ora-00001/
Row 271 failed with error: ORA-00001: unique constraint (ORA_LDING04.SYS_C002759010) violated
Help: https://docs.oracle.com/error-help/db/ora-00001/
Row 225 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 227 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 229 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 231 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 233 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 235 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 238 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 239 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 241 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 253 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 259 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 260 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 261 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 264 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 265 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 266 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 272 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 279 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 281 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 284 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 287 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Row 288 failed with error: ORA-02291: integrity constraint (ORA_LDING04.FK_RT_TO_MEDIA) violated - parent key not found
Help: https://docs.oracle.com/error-help/db/ora-02291/
Successfully inserted 209 rows.