# **Reading in the datasets (the CSV files)**

In [1]:
# Importing packages
import pandas as pd
import numpy as np


# Reading in all seven datasets. Some were previously .csv already but others need to be converted
netflix_1 = pd.read_csv("NetFlix.csv")
netflix_2 = pd.read_csv("netflix_titles.csv")
disney = pd.read_csv("disney_plus_titles.csv")
rotten_tomatoes_movies = pd.read_csv("rotten_tomatoes_movies.csv")
rotten_tomatoes_movies_reviews = pd.read_csv("rotten_tomatoes_movie_reviews.txt")
imdb_title_ratings = pd.read_csv("title.ratings.tsv", sep="\t")
imdb_title_basics = pd.read_csv("title.basics.txt", sep="\t")

## Netflix 1 Dataset

In [2]:
netflix_1.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,14-Aug-20,2020,TV-MA,4,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s10,Movie,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",India,15-Dec-17,2008,TV-MA,143,"Horror Movies, International Movies, Thrillers",An architect and his wife move into a castle t...
2,s100,Movie,3 Heroines,Iman Brotoseno,"Reza Rahadian, Bunga Citra Lestari, Tara Basro...",Indonesia,5-Jan-19,2016,TV-PG,124,"Dramas, International Movies, Sports Movies",Three Indonesian women break records by becomi...
3,s1000,Movie,Blue Mountain State: The Rise of Thadland,Lev L. Spiro,"Alan Ritchson, Darin Brooks, James Cade, Rob R...",United States,1-Mar-16,2016,R,90,Comedies,New NFL star Thad buys his old teammates' belo...
4,s1001,TV Show,Blue Planet II,NaN,David Attenborough,United Kingdom,3-Dec-18,2017,TV-G,1,"British TV Shows, Docuseries, Science & Nature TV",This sequel to the award-winning nature series...

In [3]:
print("There are", len(netflix_1), "rows in this dataset before cleaning.")

There are 7787 rows in this dataset before cleaning.

In [4]:
# Replace missing values with None so Oracle can store it as NULL
netflix_1 = netflix_1.replace({np.nan: None})
netflix_1 = netflix_1.where(pd.notnull(netflix_1), None)

# Parsing every date_added value as a date. If one is invalid, just make it missing instead of throwing an error.
netflix_1["date_added"] = pd.to_datetime(
    netflix_1["date_added"],
    format="%d-%b-%y",
    errors="coerce"
)

# Renaming the 'rating' column to 'maturity_rating' to make it more clear
netflix_1 = netflix_1.rename(columns={"rating": "maturity_rating"})

# Constraining the date added to the pandemic period [2018,2021]
netflix_1 = netflix_1[
    (netflix_1["date_added"].dt.year >= 2018) &
    (netflix_1["date_added"].dt.year <= 2021)
]

# Convert duration into a number
netflix_1["duration"] = pd.to_numeric(netflix_1["duration"], errors="coerce")

# Replace missing values again because after converting dates and numbers, pandas may have created new missing values like NaT and NaN
netflix_1 = netflix_1.where(pd.notnull(netflix_1), None)

In [5]:
netflix_1.head()

,show_id,type,title,director,cast,country,date_added,release_year,maturity_rating,duration,genres,description
0,s1,TV Show,3%,None,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,2020-08-14,2020,TV-MA,4,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
2,s100,Movie,3 Heroines,Iman Brotoseno,"Reza Rahadian, Bunga Citra Lestari, Tara Basro...",Indonesia,2019-01-05,2016,TV-PG,124,"Dramas, International Movies, Sports Movies",Three Indonesian women break records by becomi...
4,s1001,TV Show,Blue Planet II,None,David Attenborough,United Kingdom,2018-12-03,2017,TV-G,1,"British TV Shows, Docuseries, Science & Nature TV",This sequel to the award-winning nature series...
5,s1002,Movie,Blue Ruin,Jeremy Saulnier,"Macon Blair, Devin Ratray, Amy Hargreaves, Kev...","United States, France",2019-02-25,2013,R,90,"Independent Movies, Thrillers",Bad news from the past unhinges vagabond Dwigh...
6,s1003,Movie,Blue Streak,Les Mayfield,"Martin Lawrence, Luke Wilson, Peter Greene, Da...","Germany, United States",2021-01-01,1999,PG-13,94,"Action & Adventure, Comedies",A jewel thief returns to his hiding place afte...

In [6]:
print("There are", len(netflix_1), "rows in this dataset after cleaning.")

There are 5922 rows in this dataset after cleaning.

## Netflix 2 Dataset

In [7]:
netflix_2.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...

In [8]:
print("There are", len(netflix_2), "rows in this dataset before cleaning.")

There are 6234 rows in this dataset before cleaning.

In [9]:
# Replace missing values with None so Oracle can store it as NULL
netflix_2 = netflix_2.replace({np.nan: None})
netflix_2 = netflix_2.where(pd.notnull(netflix_2), None)

# Parsing every date_added value as a date. If one is invalid, just make it missing instead of throwing an error.
netflix_2["date_added"] = pd.to_datetime(
    netflix_2["date_added"],
    format="%B %d, %Y",
    errors="coerce"
)

# Renaming the 'rating' column to 'maturity_rating' to make it more clear
netflix_2 = netflix_2.rename(columns={"rating": "maturity_rating"})

# Constraining the date added to the pandemic period [2018,2021]
netflix_2 = netflix_2[
    (netflix_2["date_added"].dt.year >= 2018) &
    (netflix_2["date_added"].dt.year <= 2021)
]

# Convert duration into a number
netflix_2["duration"] = pd.to_numeric(netflix_2["duration"], errors="coerce")

# Replace missing values again because after converting dates and numbers, pandas may have created new missing values like NaT and NaN
netflix_2 = netflix_2.where(pd.notnull(netflix_2), None)

In [10]:
print("There are", len(netflix_2), "rows in this dataset after cleaning.")

There are 3860 rows in this dataset after cleaning.

In [11]:
print(netflix_2["maturity_rating"].value_counts())

maturity_rating
TV-MA       1283
TV-14       1048
R            418
TV-PG        391
PG-13        251
PG           150
TV-Y7         77
TV-G          76
TV-Y          57
NR            47
G             29
TV-Y7-FV      27
UR             4
NC-17          1
Name: count, dtype: int64

## Disney+ Dataset

In [12]:
disney.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",NaN,"November 26, 2021",2016,TV-G,23 min,"Animation, Family",Join Mickey and the gang as they duck the halls!
1,s2,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",NaN,"November 26, 2021",1988,PG,91 min,Comedy,Santa Claus passes his magic bag to a new St. ...
2,s3,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,"November 26, 2021",2011,TV-G,23 min,"Animation, Comedy, Family",Sid the Sloth is on Santa's naughty list.
3,s4,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",NaN,"November 26, 2021",2021,TV-PG,41 min,Musical,"This is real life, not just fantasy!"
4,s5,TV Show,The Beatles: Get Back,NaN,"John Lennon, Paul McCartney, George Harrison, ...",NaN,"November 25, 2021",2021,NaN,1 Season,"Docuseries, Historical, Music",A three-part documentary from Peter Jackson ca...

In [13]:
print("There are", len(disney), "rows in this dataset before cleaning.")

There are 1450 rows in this dataset before cleaning.

In [14]:
# Replace missing values with None so Oracle can store it as NULL
disney = disney.replace({np.nan: None})
disney = disney.where(pd.notnull(disney), None)

# Parsing every date_added value as a date. If one is invalid, just make it missing instead of throwing an error.
disney["date_added"] = pd.to_datetime(
    disney["date_added"],
    format="%B %d, %Y",
    errors="coerce"
)

# Renaming the 'rating' column to 'maturity_rating' to make it more clear
disney = disney.rename(columns={"rating": "maturity_rating"})

# Constraining the date added to the pandemic period [2018,2021]
disney = disney[
    (disney["date_added"].dt.year >= 2018) &
    (disney["date_added"].dt.year <= 2021)
]

# Convert duration into a number
disney["duration"] = pd.to_numeric(disney["duration"], errors="coerce")

# Replace missing values again because after converting dates and numbers, pandas may have created new missing values like NaT and NaN
disney = disney.where(pd.notnull(disney), None)

In [15]:
print("There are", len(disney), "rows in this dataset after cleaning.")

There are 1447 rows in this dataset after cleaning.

In [16]:
disney.head()

,show_id,type,title,director,cast,country,date_added,release_year,maturity_rating,duration,listed_in,description
0,s1,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",None,2021-11-26,2016,TV-G,NaN,"Animation, Family",Join Mickey and the gang as they duck the halls!
1,s2,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",None,2021-11-26,1988,PG,NaN,Comedy,Santa Claus passes his magic bag to a new St. ...
2,s3,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,2021-11-26,2011,TV-G,NaN,"Animation, Comedy, Family",Sid the Sloth is on Santa's naughty list.
3,s4,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",None,2021-11-26,2021,TV-PG,NaN,Musical,"This is real life, not just fantasy!"
4,s5,TV Show,The Beatles: Get Back,None,"John Lennon, Paul McCartney, George Harrison, ...",None,2021-11-25,2021,None,NaN,"Docuseries, Historical, Music",A three-part documentary from Peter Jackson ca...

## Rotten Tomatoes Movies Dataset

In [17]:
rotten_tomatoes_movies.head()

,id,title,audienceScore,tomatoMeter,rating,ratingContents,releaseDateTheaters,releaseDateStreaming,runtimeMinutes,genre,originalLanguage,director,writer,boxOffice,distributor,soundMix
0,space-zombie-bingo,Space Zombie Bingo!,50.0,NaN,NaN,NaN,NaN,2018-08-25,75.0,"Comedy, Horror, Sci-fi",English,George Ormrod,"George Ormrod,John Sabotta",NaN,NaN,NaN
1,the_green_grass,The Green Grass,NaN,NaN,NaN,NaN,NaN,2020-02-11,114.0,Drama,English,Tiffany Edwards,Tiffany Edwards,NaN,NaN,NaN
2,love_lies,"Love, Lies",43.0,NaN,NaN,NaN,NaN,NaN,120.0,Drama,Korean,"Park Heung-Sik,Heung-Sik Park","Ha Young-Joon,Jeon Yun-su,Song Hye-jin",NaN,NaN,NaN
3,the_sore_losers_1997,Sore Losers,60.0,NaN,NaN,NaN,NaN,2020-10-23,90.0,"Action, Mystery & thriller",English,John Michael McCarthy,John Michael McCarthy,NaN,NaN,NaN
4,dinosaur_island_2002,Dinosaur Island,70.0,NaN,NaN,NaN,NaN,2017-03-27,80.0,"Fantasy, Adventure, Animation",English,Will Meugniot,John Loy,NaN,NaN,NaN

In [18]:
print("There are", len(rotten_tomatoes_movies), "rows in this dataset before cleaning.")

There are 143258 rows in this dataset before cleaning.

In [19]:
# Rename rating to maturity_rating for clarification
rotten_tomatoes_movies = rotten_tomatoes_movies.rename(columns={"rating": "maturity_rating"})

# Drop rows with missing maturity rating
rotten_tomatoes_movies = rotten_tomatoes_movies.dropna(subset=["maturity_rating"])

# Drop rows with missing audienceScore
rotten_tomatoes_movies = rotten_tomatoes_movies.dropna(subset=["audienceScore"])

# Drop rows with missing tomatoMeter
rotten_tomatoes_movies = rotten_tomatoes_movies.dropna(subset=["tomatoMeter"])

# Standardizing the maturity ratings so it matches the Netflix and Disney+ datasets (including a dash between letters, i.e. changing TVPG to TV-PG)
rating_map = {
    "TVPG": "TV-PG",
    "TV14": "TV-14",
    "TVMA": "TV-MA",
    "TVG": "TV-G",
    "TVY7": "TV-Y7"
}

rotten_tomatoes_movies["maturity_rating"] = (
    rotten_tomatoes_movies["maturity_rating"]
    .replace(rating_map)
)

# Convert releasedateStreaming to datetime
rotten_tomatoes_movies["releaseDateStreaming"] = pd.to_datetime(
    rotten_tomatoes_movies["releaseDateStreaming"],
    errors="coerce"
)

# Keep only 2018-2021 for releasedateStreaming
rotten_tomatoes_movies = rotten_tomatoes_movies[
    rotten_tomatoes_movies["releaseDateStreaming"].dt.year.between(2018, 2021)
]

In [20]:
print("There are", len(rotten_tomatoes_movies), "rows in this dataset after cleaning.")

There are 1642 rows in this dataset after cleaning.

## IMDB Title Basics Dataset

In [21]:
imdb_title_ratings = pd.read_csv("title.ratings.tsv", sep="\t")
imdb_title_basics = pd.read_csv("title.basics.txt", sep="\t")

In [22]:
imdb_title_basics.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Poor Pierrot,Pauvre Pierrot,0,1892,\N,5,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,Short

In [23]:
print("There are", len(imdb_title_basics), "rows in this dataset before cleaning.")

There are 12287568 rows in this dataset before cleaning.

In [24]:
# Python is currently storing startYear as text, convert to numeric
imdb_title_basics["startYear"] = pd.to_numeric(
    imdb_title_basics["startYear"],
    errors="coerce"
)

# Filter to be within pandemic period [2018,2021]
imdb_title_basics = imdb_title_basics[
    imdb_title_basics["startYear"].between(2018, 2021)
]

In [25]:
print("There are", len(imdb_title_basics), "rows in this dataset after cleaning.")

There are 1905890 rows in this dataset after cleaning.

## IMDB Title Ratings Dataset

In [26]:
imdb_title_ratings.head()

      tconst  averageRating  numVotes
0  tt0000001            5.7      2192
1  tt0000002            5.5       308
2  tt0000003            6.5      2294
3  tt0000004            5.1       195
4  tt0000005            6.2      3025

In [27]:
print("There are", len(imdb_title_ratings), "rows in this dataset before cleaning.")

There are 1634568 rows in this dataset before cleaning.

In [28]:
# Only keeping the tconst that is also in the imdb_title_basics dataset. Otherwise, we would have natural left joined in SQL and it automatically would have 
# kept only the rows where the tconst is the same, but reading in the raw dataset would have exceeded the quota in Oracle.
imdb_title_ratings = imdb_title_ratings[
    imdb_title_ratings["tconst"].isin(imdb_title_basics["tconst"])
]

In [29]:
print("There are", len(imdb_title_ratings), "rows in this dataset after cleaning.")

There are 259409 rows in this dataset after cleaning.

## Writing all cleaned datasets to a new CSV

In [30]:
netflix_1.to_csv("Cleaned/netflix_1_cleaned.csv", index=False)
netflix_2.to_csv("Cleaned/netflix_2_cleaned.csv", index=False)
disney.to_csv("Cleaned/disney_cleaned.csv", index=False)
rotten_tomatoes_movies.to_csv("Cleaned/rotten_tomatoes_movies_cleaned.csv", index=False)
imdb_title_ratings.to_csv("Cleaned/imdb_title_ratings_cleaned.csv", index=False)
imdb_title_basics.to_csv("Cleaned/imdb_title_basics_cleaned.csv", index=False)