In [1]:
# try:
#     %pip install --user "oracledb" --no-warn-script-location
# except Exception as e:
#     print("\x1b[31m\u2717 Unexpected error! Please contact course staff\n" +
#          "Please include the entire text above and below in your message.")
#     raise

In [2]:
import oracledb
import csv

In [51]:
dsn = oracledb.makedsn("localhost", 1522, service_name="stu")
connection = oracledb.connect(user="ora_lding04", password="a88101027", dsn=dsn)

In [52]:
cur = connection.cursor()

## IMDB TITLE BASICS

In [5]:
cur.execute("DROP TABLE imdb_title_basics")

In [6]:
cur.execute("""
    CREATE TABLE imdb_title_basics (
        tconst VARCHAR2(20) NOT NULL PRIMARY KEY,
        titleType VARCHAR2(50),
        primaryTitle VARCHAR2(500),
        originalTitle VARCHAR2(500),
        isAdult NUMBER(1),
        startYear NUMBER(4),
        endYear NUMBER(4),
        runtimeMinutes INTEGER,
        Genres VARCHAR2(500)
    )
""")

In [7]:
import pandas as pd
import numpy as np

In [8]:
# file_path = "../datasets/title.basics.tsv"
title_basic_df = pd.read_csv("Cleaned/imdb_title_basics_cleaned.csv")
title_basic_df = title_basic_df.replace({np.nan: None})
# title_basic_df_try = title_basic_df.iloc[[0]]
# with open(file_path, 'r', encoding='utf-8') as f:
#     reader = csv.reader(f, delimiter='\t') 
#     next(reader)
#     data = [[None if col == r'\N' else col for col in row] for row in reader]
#     cur.executemany("INSERT INTO imdb_title_basics VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9)", data)

In [9]:
data_to_insert = title_basic_df.values.tolist()

In [10]:
cur.executemany("INSERT INTO imdb_title_basics VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9)", data_to_insert)
connection.commit()

## DISNEY PLUS

In [31]:
cur.execute("DROP TABLE disney_plus")

In [32]:
cur.execute("""
    CREATE TABLE disney_plus (
        show_id VARCHAR2(20) NOT NULL PRIMARY KEY,
        Type VARCHAR2(50),
        Title VARCHAR2(500),
        Director VARCHAR2(500),
        Cast VARCHAR2(500),
        Country VARCHAR2(200),
        Date_added DATE,
        release_year NUMBER(4),
        matuarity_rating VARCHAR2(10),
        duration VARCHAR2(50),
        listed_in VARCHAR2(500),
        description VARCHAR(1000)
    )
""")

In [33]:
disney_plus_df = pd.read_csv("Cleaned/disney_cleaned.csv")
disney_plus_df = disney_plus_df.replace({np.nan: None})

In [34]:
pd.DataFrame(disney_plus_df)

,show_id,type,title,director,cast,country,date_added,release_year,maturity_rating,duration,listed_in,description
0,s1,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",None,2021-11-26,2016,TV-G,None,"Animation, Family",Join Mickey and the gang as they duck the halls!
1,s2,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",None,2021-11-26,1988,PG,None,Comedy,Santa Claus passes his magic bag to a new St. ...
2,s3,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,2021-11-26,2011,TV-G,None,"Animation, Comedy, Family",Sid the Sloth is on Santa's naughty list.
3,s4,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",None,2021-11-26,2021,TV-PG,None,Musical,"This is real life, not just fantasy!"
4,s5,TV Show,The Beatles: Get Back,None,"John Lennon, Paul McCartney, George Harrison, ...",None,2021-11-25,2021,None,None,"Docuseries, Historical, Music",A three-part documentary from Peter Jackson ca...
...,...,...,...,...,...,...,...,...,...,...,...,...
1442,s1446,Movie,X-Men Origins: Wolverine,Gavin Hood,"Hugh Jackman, Liev Schreiber, Danny Huston, wi...","United States, United Kingdom",2021-06-04,2009,PG-13,None,"Action-Adventure, Family, Science Fiction",Wolverine unites with legendary X-Men to fight...
1443,s1447,Movie,Night at the Museum: Battle of the Smithsonian,Shawn Levy,"Ben Stiller, Amy Adams, Owen Wilson, Hank Azar...","United States, Canada",2021-04-02,2009,PG,None,"Action-Adventure, Comedy, Family",Larry Daley returns to rescue some old friends...
1444,s1448,Movie,Eddie the Eagle,Dexter Fletcher,"Tom Costello, Jo Hartley, Keith Allen, Dickon ...","United Kingdom, Germany, United States",2020-12-18,2016,PG-13,None,"Biographical, Comedy, Drama","True story of Eddie Edwards, a British ski-jum..."
1445,s1449,Movie,Bend It Like Beckham,Gurinder Chadha,"Parminder Nagra, Keira Knightley, Jonathan Rhy...","United Kingdom, Germany, United States",2020-09-18,2003,PG-13,None,"Buddy, Comedy, Coming of Age",Despite the wishes of their traditional famili...
1446,s1450,Movie,Captain Sparky vs. The Flying Saucers,Mark Waring,Charlie Tahan,United States,2020-04-01,2012,TV-G,None,"Action-Adventure, Animals & Nature, Animation",View one of Sparky's favorite home movies.

In [35]:
data_to_insert_disney = disney_plus_df.values.tolist()

In [36]:
cur.executemany("INSERT INTO disney_plus VALUES (:1, :2, :3, :4, :5, :6, TO_DATE(:7, 'YYYY-MM-DD'), :8, :9, :10, :11, :12)", data_to_insert_disney)
connection.commit()

## NETFLIX_1

In [44]:
cur.execute("DROP TABLE netflix_1")

In [45]:
cur.execute("""
    CREATE TABLE netflix_1 (
        show_id VARCHAR2(20) NOT NULL PRIMARY KEY,
        Type VARCHAR2(50),
        Title VARCHAR2(500),
        Director VARCHAR2(500),
        Cast VARCHAR2(1000),
        Country VARCHAR2(200),
        Date_added DATE,
        release_year NUMBER(4),
        matuarity_rating VARCHAR2(10),
        duration VARCHAR2(50),
        genres VARCHAR2(500),
        description VARCHAR(1000)
    )
""")

In [38]:
netflix_1_df = pd.read_csv("Cleaned/netflix_1_cleaned.csv")
netflix_1_df = netflix_1_df.replace({np.nan: None})

In [39]:
pd.DataFrame(netflix_1_df)

,show_id,type,title,director,cast,country,date_added,release_year,maturity_rating,duration,genres,description
0,s1,TV Show,3%,None,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,2020-08-14,2020,TV-MA,4,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s100,Movie,3 Heroines,Iman Brotoseno,"Reza Rahadian, Bunga Citra Lestari, Tara Basro...",Indonesia,2019-01-05,2016,TV-PG,124,"Dramas, International Movies, Sports Movies",Three Indonesian women break records by becomi...
2,s1001,TV Show,Blue Planet II,None,David Attenborough,United Kingdom,2018-12-03,2017,TV-G,1,"British TV Shows, Docuseries, Science & Nature TV",This sequel to the award-winning nature series...
3,s1002,Movie,Blue Ruin,Jeremy Saulnier,"Macon Blair, Devin Ratray, Amy Hargreaves, Kev...","United States, France",2019-02-25,2013,R,90,"Independent Movies, Thrillers",Bad news from the past unhinges vagabond Dwigh...
4,s1003,Movie,Blue Streak,Les Mayfield,"Martin Lawrence, Luke Wilson, Peter Greene, Da...","Germany, United States",2021-01-01,1999,PG-13,94,"Action & Adventure, Comedies",A jewel thief returns to his hiding place afte...
...,...,...,...,...,...,...,...,...,...,...,...,...
5917,s993,TV Show,Bloodride,None,"Ine Marie Wilmann, Bjørnar Teigen, Emma Spetal...",Norway,2020-03-13,2020,TV-MA,1,"International TV Shows, TV Horror, TV Mysteries",The doomed passengers aboard a spectral bus he...
5918,s994,Movie,Blow,Ted Demme,"Johnny Depp, Penélope Cruz, Franka Potente, Ra...",United States,2019-10-01,2001,R,123,Dramas,Cocaine smuggler George rises from poverty to ...
5919,s995,TV Show,Blown Away,None,None,Canada,2019-07-12,2019,TV-14,1,"International TV Shows, Reality TV",Ten master artists turn up the heat in glassbl...
5920,s996,TV Show,Blue Exorcist,None,"Nobuhiko Okamoto, Jun Fukuyama, Kana Hanazawa,...",Japan,2020-09-01,2017,TV-MA,2,"Anime Series, International TV Shows",Determined to throw off the curse of being Sat...
5921,s998,Movie,Blue Jasmine,Woody Allen,"Cate Blanchett, Sally Hawkins, Alec Baldwin, L...",United States,2019-03-08,2013,PG-13,98,"Comedies, Dramas, Independent Movies",The high life leads to high anxiety for a fash...

In [40]:
data_to_insert_netflix = netflix_1_df.values.tolist()

In [46]:
cur.executemany("INSERT INTO netflix_1 VALUES (:1, :2, :3, :4, :5, :6, TO_DATE(:7, 'YYYY-MM-DD'), :8, :9, :10, :11, :12)", data_to_insert_netflix)
connection.commit()

## NETFLIX_2

In [47]:
netflix_2_df = pd.read_csv("Cleaned/netflix_2_cleaned.csv")
netflix_2_df = netflix_2_df.replace({np.nan: None})

In [48]:
pd.DataFrame(netflix_2_df)

,show_id,type,title,director,cast,country,date_added,release_year,maturity_rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019-09-09,2019,TV-PG,None,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,70234439,TV Show,Transformers Prime,None,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2018-09-08,2013,TV-Y7-FV,None,Kids' TV,"With the help of three human allies, the Autob..."
2,80058654,TV Show,Transformers: Robots in Disguise,None,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2018-09-08,2016,TV-Y7,None,Kids' TV,When a prison ship crash unleashes hundreds of...
3,80244601,TV Show,Castle of Stars,None,"Chaiyapol Pupart, Jintanutda Lummakanon, Worra...",None,2018-09-07,2015,TV-14,None,"International TV Shows, Romantic TV Shows, TV ...",As four couples with different lifestyles go t...
4,80203094,Movie,City of Joy,Madeleine Gavin,None,"United States,",2018-09-07,2018,TV-MA,None,Documentaries,Women who've been sexually brutalized in war-t...
...,...,...,...,...,...,...,...,...,...,...,...,...
3855,80049281,Movie,Secret in Their Eyes,Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...","United States, United Kingdom, Spain, South Korea",2018-04-01,2015,PG-13,None,"Dramas, Thrillers",A former FBI investigator reopens the haunting...
3856,70084328,Movie,The Aerial,Esteban Sapir,"Rafael Ferro, Sol Moreno, Jonathan Sandor, Ale...",Argentina,2018-04-01,2007,TV-MA,None,"Dramas, International Movies, Sci-Fi & Fantasy","In the City Without a Voice, only faceless sin..."
3857,70099610,Movie,The Duchess,Saul Dibb,"Keira Knightley, Ralph Fiennes, Charlotte Ramp...","United Kingdom, Italy, France, United States",2018-04-01,2008,PG-13,None,"Dramas, International Movies, Romantic Movies","To compensate for her unhappy marriage, young ..."
3858,80217041,Movie,The Search for Life in Space,Stephen Amezdroz,None,United States,2018-04-01,2016,TV-G,None,Documentaries,To determine whether we're alone in the univer...
3859,80156408,Movie,Una,Benedict Andrews,"Rooney Mara, Ben Mendelsohn, Riz Ahmed, Ruby S...","United Kingdom, Canada, United States",2018-04-01,2016,R,None,"Dramas, International Movies",A young woman tracks down the older man who pr...

In [53]:
cur.execute("""
    CREATE TABLE netflix_2 (
        show_id VARCHAR2(20) NOT NULL PRIMARY KEY,
        Type VARCHAR2(50),
        Title VARCHAR2(500),
        Director VARCHAR2(500),
        Cast VARCHAR2(1000),
        Country VARCHAR2(200),
        Date_added DATE,
        release_year NUMBER(4),
        matuarity_rating VARCHAR2(10),
        duration VARCHAR2(50),
        listed_in VARCHAR2(500),
        description VARCHAR(1000)
    )
""")

In [54]:
data_to_insert_netflix_2 = netflix_2_df.values.tolist()

In [55]:
cur.executemany("INSERT INTO netflix_2 VALUES (:1, :2, :3, :4, :5, :6, TO_DATE(:7, 'YYYY-MM-DD'), :8, :9, :10, :11, :12)", data_to_insert_netflix_2)
connection.commit()

DatabaseError: ORA-01536: space quota exceeded for tablespace 'USERS'
Help: https://docs.oracle.com/error-help/db/ora-01536/