In [5]:
try:
    %pip install --user "oracledb" --no-warn-script-location
except Exception as e:
    print("\x1b[31m\u2717 Unexpected error! Please contact course staff\n" +
         "Please include the entire text above and below in your message.")
    raise

Requirement already satisfied: oracledb in /home/jupyter/.local/lib/python3.13/site-packages (3.4.2)
Requirement already satisfied: cryptography>=3.2.1 in /opt/conda/lib/python3.13/site-packages (from oracledb) (46.0.2)
Requirement already satisfied: typing_extensions>=4.14.0 in /opt/conda/lib/python3.13/site-packages (from oracledb) (4.15.0)
Requirement already satisfied: cffi>=1.14 in /opt/conda/lib/python3.13/site-packages (from cryptography>=3.2.1->oracledb) (2.0.0)
Requirement already satisfied: pycparser in /opt/conda/lib/python3.13/site-packages (from cffi>=1.14->cryptography>=3.2.1->oracledb) (2.22)
Note: you may need to restart the kernel to use updated packages.

In [6]:
import oracledb
dsn = oracledb.makedsn("localhost", 1522, service_name="stu")
connection = oracledb.connect(user="ora_kshih02", password="a52570777", dsn=dsn)

In [7]:
import pandas as pd
import numpy as np

## Loading in Python + EDA

## Rotten Tomatoes Kaggle Dataset
Description: A rotten tomatoes dataset, we use the rotten_tomatoes_movies.csv and the  rotten_tomatoes_movie_reviews. The title and rating are the foreign key referencing the title and rating in the movie dataset.
<br>
Size/scope: 142052 rows, 16 columns
Variables/attributes:
rottentomatoes_movies (id, title, audienceScore, tomatoMeter, rating, ratingContents, releaseDateTheaters, releaseDateStreaming, runtimeMinutes, genre)
rottentomatoes_movies_reviews(id, reviewId, creationDate, criticName, isTopCritic, originalScore, reviewState, publicatioName, reviewText, scoreSentiment)

### EDA of `rotten_tomatoes_movies.csv`

In [8]:
rt_mov = pd.read_csv("datasets/rotten_tomatoes_movies.csv")
rt_mov.head(3)

,id,title,audienceScore,tomatoMeter,rating,ratingContents,releaseDateTheaters,releaseDateStreaming,runtimeMinutes,genre,originalLanguage,director,writer,boxOffice,distributor,soundMix
0,space-zombie-bingo,Space Zombie Bingo!,50.0,NaN,NaN,NaN,NaN,2018-08-25,75.0,"Comedy, Horror, Sci-fi",English,George Ormrod,"George Ormrod,John Sabotta",NaN,NaN,NaN
1,the_green_grass,The Green Grass,NaN,NaN,NaN,NaN,NaN,2020-02-11,114.0,Drama,English,Tiffany Edwards,Tiffany Edwards,NaN,NaN,NaN
2,love_lies,"Love, Lies",43.0,NaN,NaN,NaN,NaN,NaN,120.0,Drama,Korean,"Park Heung-Sik,Heung-Sik Park","Ha Young-Joon,Jeon Yun-su,Song Hye-jin",NaN,NaN,NaN

In [17]:
rt_mov.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143258 entries, 0 to 143257
Data columns (total 16 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    143258 non-null  object
 1   title                 142891 non-null  object
 2   audienceScore         73248 non-null   float64
 3   tomatoMeter           33877 non-null   float64
 4   rating                13991 non-null   object
 5   ratingContents        13991 non-null   object
 6   releaseDateTheaters   30773 non-null   object
 7   releaseDateStreaming  79420 non-null   object
 8   runtimeMinutes        129431 non-null  float64
 9   genre                 132175 non-null  object
 10  originalLanguage      129400 non-null  object
 11  director              139041 non-null  object
 12  writer                90116 non-null   object
 13  boxOffice             14743 non-null   object
 14  distributor           23001 non-null   object
 15  soundMix              15917 non-null   object
dtypes: float64(3), object(13)
memory usage: 17.5+ MB

In [14]:
# rt_mov_review = pd.read_csv("datasets/rotten_tomatoes_movie_reviews.csv")
# rt_mov_review.head(3)

## Disney Movies & TV Shows Kaggle
Description: a dataset of disney+ movies and tv shows. The Title and Release_year are the foreign key referencing the imdb dataset. The title and rating are the foreign key referencing the rotten tomatoes dataset.
<br>
Size/scope: 1450 rows, 12 columns
Variables/attributes:
DIsney+(Show_id, Type, Title, Director, Cast, Country, Date_added, Release_year, rating, duration)

### EDA of `datasets/disney_plus_titles.csv`

In [25]:
disney_titles = pd.read_csv("datasets/disney_plus_titles.csv")
disney_titles.head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",NaN,"November 26, 2021",2016,TV-G,23 min,"Animation, Family",Join Mickey and the gang as they duck the halls!
1,s2,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",NaN,"November 26, 2021",1988,PG,91 min,Comedy,Santa Claus passes his magic bag to a new St. ...
2,s3,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,"November 26, 2021",2011,TV-G,23 min,"Animation, Comedy, Family",Sid the Sloth is on Santa's naughty list.

In [19]:
disney_titles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1450 entries, 0 to 1449
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       1450 non-null   object
 1   type          1450 non-null   object
 2   title         1450 non-null   object
 3   director      977 non-null    object
 4   cast          1260 non-null   object
 5   country       1231 non-null   object
 6   date_added    1447 non-null   object
 7   release_year  1450 non-null   int64
 8   rating        1447 non-null   object
 9   duration      1450 non-null   object
 10  listed_in     1450 non-null   object
 11  description   1450 non-null   object
dtypes: int64(1), object(11)
memory usage: 136.1+ KB

## Netflix Dataset 1 Kaggle
Description: A dataset of Netflix movies and tv shows. The rating attribute in this dataset is the maturity rating. The Title and Release_year are the foreign key referencing the IMDb dataset. The title and rating are the foreign key referencing the Rotten Tomatoes dataset.

Size/scope: 6234 rows, 12 columns
Variables/attributes:
Netflix(Show_id, Type, Title, Director, Cast, Country, Date_added, Release_year, rating, duration)

In [10]:
netflix_titles = pd.read_csv("datasets/netflix_titles.csv")
netflix_titles.head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."

In [20]:
netflix_titles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6234 entries, 0 to 6233
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       6234 non-null   int64
 1   type          6234 non-null   object
 2   title         6234 non-null   object
 3   director      4265 non-null   object
 4   cast          5664 non-null   object
 5   country       5758 non-null   object
 6   date_added    6223 non-null   object
 7   release_year  6234 non-null   int64
 8   rating        6224 non-null   object
 9   duration      6234 non-null   object
 10  listed_in     6234 non-null   object
 11  description   6234 non-null   object
dtypes: int64(2), object(10)
memory usage: 584.6+ KB

## Netflix Dataset 2 Kaggle
Description: A dataset of Netflix movies and tv shows. The Title and Release_year are the foreign key referencing the IMDb dataset. The title and rating are the foreign key referencing the Rotten Tomatoes dataset.

Size/scope: 7787 rows, 12 columns
Variables/attributes:
Netflix2(Show_id, Type, Title, Director, Cast, Country, Date_added, Release_year, rating, duration)

In [11]:
netflix = pd.read_csv("datasets/NetFlix.csv")
netflix.head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,14-Aug-20,2020,TV-MA,4,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s10,Movie,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",India,15-Dec-17,2008,TV-MA,143,"Horror Movies, International Movies, Thrillers",An architect and his wife move into a castle t...
2,s100,Movie,3 Heroines,Iman Brotoseno,"Reza Rahadian, Bunga Citra Lestari, Tara Basro...",Indonesia,5-Jan-19,2016,TV-PG,124,"Dramas, International Movies, Sports Movies",Three Indonesian women break records by becomi...

In [22]:
netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      5398 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7777 non-null   object
 7   release_year  7787 non-null   int64
 8   rating        7780 non-null   object
 9   duration      7787 non-null   int64
 10  genres        7787 non-null   object
 11  description   7787 non-null   object
dtypes: int64(2), object(10)
memory usage: 730.2+ KB

## IMDB Dataset (using the title.rating.tsv.gz and title.basics.tsv.gz datasets)
Description: we will only look at the title.rating dataset and the title.basics dataset. The primary title and the start year are the foreign key referencing the title and release_year in the movies dataset.

Size/scope: 1,634,532 rows
Variables/attributes:
title.basics(Tconst, Title Type, Primary Title, Original Title, Is Adult, Start Year, End Year, Runtime Minutes, Genres)
title.ratings(Tconst, Average Rating, Num Votes)

In [12]:
title_ratings = pd.read_csv("datasets/title.ratings.tsv", sep="\t")
title_ratings.head(3)

      tconst  averageRating  numVotes
0  tt0000001            5.7      2192
1  tt0000002            5.5       308
2  tt0000003            6.5      2294

In [24]:
title_ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1634568 entries, 0 to 1634567
Data columns (total 3 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   tconst         1634568 non-null  object
 1   averageRating  1634568 non-null  float64
 2   numVotes       1634568 non-null  int64
dtypes: float64(1), int64(1), object(1)
memory usage: 37.4+ MB

## Oracle Sql Table Creation
### Movies
- creating movie table unioning netflix 1 netflix 2 and disney

In [ ]:
create_table_movies = """
    CREATE TABLE movies (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY,
        first_name VARCHAR2(50) NOT NULL,
        last_name VARCHAR2(50) NOT NULL,
        email VARCHAR2(100),
        hire_date DATE DEFAULT SYSDATE,
        PRIMARY KEY (id)
    )
    """

## Research Question Hypthesis
### Research question: 

We will examine whether professional critics, and general audiences evaluated movies released on streaming platforms (e.g., Netflix, Disney+) differently before (2018, 2019) and during the height of (2020, 2021) the COVID-19 pandemic, using data from Rotten Tomatoes and IMDb for films available between 2018 and 2021. 

1) What is the impact of the COVID-19 pandemic on changing audience/viewer sentiment towards all movies measured by average IMDb rating? 

2) What proportion of movies had higher Rotten Tomatoes critic scores (Tomatometer) than audience scores (Popcornmeter) in the pre-pandemic (2018-2019) and peak pandemic (2020-2021) periods? 

3) How did the COVID-19 pandemic affect the weighted-average rating patterns across different maturity ratings of media? More specifically, is there a statistically significant change between Parental-Guided rated movies (PG-13 + TV-PG + TV-14) vs Mature / Adult rated movies (R + TV-MA)?

### Evaluation Method/ Methodology:
We will evaluate our data using a comparative approach. We will split the dataset into the pre-pandemic (2018-2019) and peak-pandemic (2020-2021) periods and compute summary statistics for IMDb ratings, Rotten Tomatoes critic scores, and audience scores.
To test for statistically significant changes in average IMDb ratings across periods (Question 1), we will use two-sample t-tests.
We will then compare the proportion of films (Question 2) where the Tomatometer exceeds the Popcornmeter, which are the critics and audience scores, respectively, in each period using difference-in-proportions tests.
Lastly, we will calculate vote-weighted average ratings and use two-sample t-tests within each age-rating category to test for statistically significant differences between the two periods.
4. Hypothesis:

1) There is a statistically significant increase in the average IMDb rating for movies and TV shows released between the height of COVID-19 (2020, 2021) and 2018-2019, likely due to increased consumption and greater access to entertainment, with algorithms curated to users' tastes. 
2) The gap between Rotten Tomatoes’ Tomatometer (Critics) and Popcornmeter (Audience) scores widened significantly during the pandemic (2020-2021) compared to the pre-pandemic baseline, as critics focused on quality, while the general audience consumed more content to pass the time. 
3) During the pandemic, mature-rated media (R and TV-MA) showed an increase in total vote volume and a more consistent weighted-average rating than Parental-Guidance-rated media (PG-13, TV-PG, and TV-14). This divergence is primarily attributable to the transition in entertainment consumption from conventional cinema to digital streaming platforms (e.g., Netflix, Disney+).

## SQL Query 1
**Research question 1:** What is the impact of the COVID-19 pandemic on changing audience/viewer sentiment towards all movies measured by average IMDb rating?
<br>
**Hypothesis 1:** There is a statistically significant increase in the average IMDb rating for movies and TV shows released between the height of COVID-19 (2020, 2021) and 2018-2019, likely due to increased consumption and greater access to entertainment, with algorithms curated to users' tastes.